export default
{
  "debug": false,
  "imgHost": "http://test-pic.energyiot.cn",
  "websocketUrl": "http://dev-m.energyiot.cn/ws",
  "push": "manage/configur/push",
  "get": "manage/configur/canvas/get",
  "save": "manage/configur/canvas/save",
  "organizList": "manage/orgStruc/listByLevel",
  "devicePoints": "manage/configur/common/devicePoints",
  "upload": "manage/upload/upload2Oss",
  "getDevice": "manage/configur/common/getDevice",
  "deviceList": "manage/configur/common/deviceList",
  "devicePointHstData": "manage/configur/common/devicePointHstData",
  "control": "manage/configur/canvas/control",
  "token": "manage/configur/canvas/token",
  "start": "manage/configur/canvas/start",
  "stop": "manage/configur/canvas/stop",
  service: {
    "debug": false,
    "imgHost": "http://test-pic.energyiot.cn",
    "websocketUrl": "http://dev-eiot.energyiot.cn/ws",
    "push": "service/configur/push",
    "get": "service/configur/canvas/get",
    "control": "service/configur/canvas/control",
    "token": "service/configur/canvas/token",
    "start": "service/configur/canvas/start",
    "stop": "service/configur/canvas/stop",
    "getDevice": "service/configur/common/getDevice",
    "deviceList": "service/configur/common/deviceList",
    "devicePointHstData": "service/configur/common/devicePointHstData",
    "control": "service/configur/canvas/control",
    "token": "service/configur/canvas/token",
    "start": "service/configur/canvas/start",
    "stop": "service/configur/canvas/stop",
  }
}
